# https://github.com/google/mono_repo.dart
#sdk:
#- 2.12.0
#- dev

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
  - group:
    - analyze: .
    sdk: pubspec

#- unit_test:
#  - test
