targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          checked: true
          create_to_json: false
          disallow_unrecognized_keys: true
          field_rename: kebab

      # The end-user of a builder which applies "source_gen|combining_builder"
      # may configure the builder to ignore specific lints for their project
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - deprecated_member_use_from_same_package
          - lines_longer_than_80_chars
          - prefer_expression_function_bodies
