# Created with package:mono_repo v6.4.0
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.4.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_format; linux; Dart 2.17.0; PKGS: example/web_app, example/web_server, shelf_dev; `dart analyze .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:example/web_app-example/web_server-shelf_dev;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: "2.17.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: example_web_app_pub_upgrade
        name: example/web_app; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
      - name: example/web_app; dart analyze .
        run: dart analyze .
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
      - name: example/web_server; dart analyze .
        run: dart analyze .
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: shelf_dev; dart analyze .
        run: dart analyze .
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
  job_003:
    name: "analyze_format; linux; Dart dev; PKGS: example/web_app, example/web_server, shelf_dev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example/web_app-example/web_server-shelf_dev;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: example_web_app_pub_upgrade
        name: example/web_app; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
      - name: "example/web_app; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
      - name: "example/web_app; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
      - name: "example/web_server; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
      - name: "example/web_server; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: "shelf_dev; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
      - name: "shelf_dev; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
  job_004:
    name: "unit_test; linux; Dart 2.17.0; PKG: example/web_server; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:example/web_server;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: "2.17.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
      - name: example/web_server; dart test
        run: dart test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; linux; Dart 2.17.0; PKG: shelf_dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:shelf_dev;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: "2.17.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: shelf_dev; dart test
        run: dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; linux; Dart dev; PKG: example/web_server; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example/web_server;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
      - name: example/web_server; dart test
        run: dart test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
    needs:
      - job_001
      - job_002
      - job_003
  job_007:
    name: "unit_test; linux; Dart dev; PKG: shelf_dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:shelf_dev;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: shelf_dev; dart test
        run: dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
    needs:
      - job_001
      - job_002
      - job_003
  job_008:
    name: "unit_test; linux; Dart dev; PKG: shelf_dev; `dart test --run-skipped -t presubmit-only`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:shelf_dev;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: "shelf_dev; dart test --run-skipped -t presubmit-only"
        run: dart test --run-skipped -t presubmit-only
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
    needs:
      - job_001
      - job_002
      - job_003
  job_009:
    name: "unit_test; windows; Dart 2.17.0; PKG: shelf_dev; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: "2.17.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: shelf_dev; dart test
        run: dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
    needs:
      - job_001
      - job_002
      - job_003
  job_010:
    name: "unit_test; windows; Dart dev; PKG: shelf_dev; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
      - name: shelf_dev; dart test
        run: dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
    needs:
      - job_001
      - job_002
      - job_003
