# Created with package:mono_repo v3.4.7
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - name: mono_repo self validate
        run: pub global activate mono_repo 3.4.7
      - name: mono_repo self validate
        run: pub global run mono_repo generate --validate
  job_002:
    name: "analyze_format; Dart dev; PKGS: example/web_app, example/web_server, shelf_dev; `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_app-example/web_server-shelf_dev;commands:dartfmt-dartanalyzer_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2
      - id: example_web_app_pub_upgrade
        name: "example/web_app; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
        run: pub upgrade --no-precompile
      - name: "example/web_app; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: dartfmt -n --set-exit-if-changed .
      - name: "example/web_app; dartanalyzer --fatal-infos ."
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: dartanalyzer --fatal-infos .
      - id: example_web_server_pub_upgrade
        name: "example/web_server; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: pub upgrade --no-precompile
      - name: "example/web_server; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dartfmt -n --set-exit-if-changed .
      - name: "example/web_server; dartanalyzer --fatal-infos ."
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dartanalyzer --fatal-infos .
      - id: shelf_dev_pub_upgrade
        name: "shelf_dev; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub upgrade --no-precompile
      - name: "shelf_dev; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dartfmt -n --set-exit-if-changed .
      - name: "shelf_dev; dartanalyzer --fatal-infos ."
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dartanalyzer --fatal-infos .
  job_003:
    name: "analyze_format; Dart 2.12.0; PKGS: example/web_app, example/web_server, shelf_dev; `dartanalyzer .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_app-example/web_server-shelf_dev;commands:dartanalyzer_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2
      - id: example_web_app_pub_upgrade
        name: "example/web_app; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
        run: pub upgrade --no-precompile
      - name: example/web_app; dartanalyzer .
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: dartanalyzer .
      - id: example_web_server_pub_upgrade
        name: "example/web_server; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: pub upgrade --no-precompile
      - name: example/web_server; dartanalyzer .
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dartanalyzer .
      - id: shelf_dev_pub_upgrade
        name: "shelf_dev; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub upgrade --no-precompile
      - name: shelf_dev; dartanalyzer .
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dartanalyzer .
  job_004:
    name: "unit_test; Dart 2.12.0; PKG: example/web_server; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_server;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2
      - id: example_web_server_pub_upgrade
        name: "example/web_server; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: pub upgrade --no-precompile
      - name: example/web_server; pub run test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; Dart 2.12.0; PKG: shelf_dev; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:shelf_dev;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2
      - id: shelf_dev_pub_upgrade
        name: "shelf_dev; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub upgrade --no-precompile
      - name: shelf_dev; pub run test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; Dart dev; PKG: example/web_server; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_server;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2
      - id: example_web_server_pub_upgrade
        name: "example/web_server; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: pub upgrade --no-precompile
      - name: example/web_server; pub run test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
  job_007:
    name: "unit_test; Dart dev; PKG: shelf_dev; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2
      - id: shelf_dev_pub_upgrade
        name: "shelf_dev; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub upgrade --no-precompile
      - name: shelf_dev; pub run test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
