# Created with package:mono_repo v5.0.0
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_format; linux; Dart 2.12.0; PKGS: example/web_app, example/web_server, shelf_dev; `dart analyze .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_app-example/web_server-shelf_dev;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: example_web_app_pub_upgrade
        name: example/web_app; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
        run: dart pub upgrade
      - name: example/web_app; dart analyze .
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: dart analyze .
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: dart pub upgrade
      - name: example/web_server; dart analyze .
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dart analyze .
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: shelf_dev; dart analyze .
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart analyze .
  job_003:
    name: "analyze_format; linux; Dart dev; PKGS: example/web_app, example/web_server, shelf_dev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_app-example/web_server-shelf_dev;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_app-example/web_server-shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: example_web_app_pub_upgrade
        name: example/web_app; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_app
        run: dart pub upgrade
      - name: "example/web_app; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "example/web_app; dart analyze --fatal-infos ."
        if: "always() && steps.example_web_app_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_app
        run: dart analyze --fatal-infos .
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: dart pub upgrade
      - name: "example/web_server; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "example/web_server; dart analyze --fatal-infos ."
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dart analyze --fatal-infos .
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: "shelf_dev; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "shelf_dev; dart analyze --fatal-infos ."
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart analyze --fatal-infos .
  job_004:
    name: "unit_test; linux; Dart 2.12.0; PKG: example/web_server; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_server;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: dart pub upgrade
      - name: example/web_server; dart test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; linux; Dart 2.12.0; PKG: shelf_dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:shelf_dev;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: shelf_dev; dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; linux; Dart dev; PKG: example/web_server; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_server;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example/web_server
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: example_web_server_pub_upgrade
        name: example/web_server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example/web_server
        run: dart pub upgrade
      - name: example/web_server; dart test
        if: "always() && steps.example_web_server_pub_upgrade.conclusion == 'success'"
        working-directory: example/web_server
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_007:
    name: "unit_test; linux; Dart dev; PKG: shelf_dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: shelf_dev; dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_008:
    name: "unit_test; linux; Dart dev; PKG: shelf_dev; `dart test --run-skipped -t presubmit-only`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:shelf_dev
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: "shelf_dev; dart test --run-skipped -t presubmit-only"
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart test --run-skipped -t presubmit-only
    needs:
      - job_001
      - job_002
      - job_003
  job_009:
    name: "unit_test; windows; Dart 2.12.0; PKG: shelf_dev; `dart test`"
    runs-on: windows-latest
    steps:
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: shelf_dev; dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_010:
    name: "unit_test; windows; Dart dev; PKG: shelf_dev; `dart test`"
    runs-on: windows-latest
    steps:
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: shelf_dev_pub_upgrade
        name: shelf_dev; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart pub upgrade
      - name: shelf_dev; dart test
        if: "always() && steps.shelf_dev_pub_upgrade.conclusion == 'success'"
        working-directory: shelf_dev
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
